# Generated by Django 6.0.5 on 2026-05-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at']},
        ),
    ]
