# Generated by Django 6.0.5 on 2026-05-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
